
on:
  push:
    branches:
      - master



jobs:
  deploy-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      - run: echo "successfull deployment!!!!!"
